### ISSUE TITLE
TRACKING ISSUE -> Include some interesting ideas into plonk codebase

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/plonk#237]
Currently we have some issues with good ideas or enhancements on them:
- [ ] Move assert_eq to perm poly instead of using a gate. #218
- [x] Create a prelude file to export all of the things we consider important. #227
- [x] Split `Prover` and `Verifier` keys #212
- [ ] Cache challenges on a transcript abstraction #242 
- [ ] Split poly computations between Prover and Verifier mods respectively #241 
- [x] Gate specific methods to their own files. #240 
- [ ] Cleanup Permutation module #239

**Comment by kevaundray** [comment]
Is this issue needed? We have separate issues open for each and they are not related except for them being "interesting" ?

**Comment by CPerezz** [comment]
Is the only way I have to pack these issues in Epics for plonk mate.. I know looks weird but my idea was to have these issues as tracking issues. So they are epics and expose all of the issues related or "packed" into them.
